#!/usr/bin/env bash

set -Eeuo pipefail

init_wpfx() {
    local udk=${1}
    local udk_srcpath=${2}
    local engine_conf_in=${3}
    local engine_conf_out=${4}
    shift 4

    env | grep WINE
    rm -rf "${WINEPREFIX}"
    mkdir -p "${WINEPREFIX}"
    wineboot
    WINETRICKS_LATEST_VERSION_CHECK=disabled winetricks --unattended dotnet40
    wine "${udk}" -ProgressOnly
    wineserver -w

    for d in "${udk_srcpath}/"*; do
        cp -af --reflink=auto "${d}"{,_sample}
    done

    mv -f "${engine_conf_in}" "${engine_conf_out}"
    touch "${engine_conf_out}"
}

lwce_udk() {
    local udk_srcpath=${1}
    local src_root=${2}
    local engine_conf_in=${3}
    local engine_conf_out=${4}
    shift 4

    relpath=$(echo "${udk_srcpath}" | sed -e "s#^${src_root}/##g" -e 's#[^/]\+#..#g')
    for d in "${@}"; do
        if [[ -d "${src_root}/Stubs/${d}" ]]; then
            rm -rf "${udk_srcpath:?}/${d}"
            ln -sfT "${relpath}/Stubs/${d}" "${udk_srcpath}/${d}"
        elif [[ -d "${src_root}/Src/${d}" ]]; then
            ln -sfT "${relpath}/Src/${d}" "${udk_srcpath}/${d}"
        else
            echo "Missing package: ${d}" >&2
            exit 1
        fi
    done

    sample_config="$(printf '+EditPackages=%s\\r\\n' 'UTGame' 'UTGameContent')"
    lwce_config="$(printf '+EditPackages=%s\\r\\n' "${@}")"
    sed -z -e "s@${sample_config}@${lwce_config}@g" \
        "${engine_conf_in}" > "${engine_conf_out}"
}

lwce_build() {
    local udk=${1}
    shift

    cd "${udk}/Binaries"
    wine Win32/UDK.com make || echo "ERROR: build failed: $?"
    wineserver -w
}

cmd=${1}
shift

"${cmd}" "${@}"
