/*******************************************************************************
 * UIStrategyHUD_FSM_Engineering generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class UIStrategyHUD_FSM_Engineering extends UIStrategyHUD_FacilitySubMenu
    hidecategories(Navigation);