/*******************************************************************************
 * UITellMeMore generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class UITellMeMore extends UI_FxsShellScreen
    config(GameData)
    hidecategories(Navigation)
    implements(IScreenMgrInterface);

enum ECategoryTMM
{
    Category_Barracks,
    Category_Science,
    Category_MissionControl,
    Category_SituationRoom,
    Category_Engineering,
    Category_Hangar,
    Category_MAX
};

struct TItemData
{
    var UITellMeMore.ECategoryTMM Category;
    var string Label;
    var string Desc;
    var string imgPath;
    var string Sound;
};

struct TSection
{
    var string Label;
    var string imgPath;
    var bool bClosed;
    var array<TItemData> Items;

    structdefaultproperties
    {
        bClosed=true
    }
};

struct UIOption
{
    var int iIndex;
    var string strLabel;
    var string strDesc;
    var string strImgPath;
    var string soundPath;
    var int iState;
    var string strHelp;
    var int sectionIdx;

    structdefaultproperties
    {
        iIndex=-1
        strLabel="Default Label"
        sectionIdx=-1
    }
};

var const localized string m_strTellMeMoreSelectTitle;
var private int m_iCurrentSelection;
var private int m_iPlayedSelection;
var protected array<UIOption> m_arrUIOptions;
var protected int m_iView;
var config array<config TItemData> TellMeMoreItems;
var config array<config TSection> Sections;
var XComHeadquartersInput HQINPUT;
var XComNarrativeMoment ItemNarrative;
var bool m_bOldDisableAccept;
var bool m_bOldDisableCancel;
var bool m_bOldDisableLeftStick;
var bool m_bOldDisableRightStick;
var bool m_bOldDisableDPad;
var bool m_bOldDisableBumpers;

defaultproperties
{
    m_iPlayedSelection=-1
    s_package="/ package/gfxTellMeMore/TellMeMore"
    s_screenId="gfxTellMeMore"
    e_InputState=eInputState_Consume
    s_name=TellMeMoreMC
}