/*******************************************************************************
 * XComHQPresentationLayer generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XComHQPresentationLayer extends XComPresentationLayerBase
    hidecategories(Navigation);

var protected XGHQCamera m_kCamera;
var XComHQSoundCollection m_kSounds;
var XGSoundMgr m_kSoundMgr;
var XComDropshipAudioMgr m_kMissionAudioMgr;
var protected UIAlert m_kUIAlert;
var protected UIBaseFinances m_kFinances;
var UIBriefing m_kBriefing;
var protected UIDropshipHUD m_kPCDropshipHUD;
var UIBuildFacilities m_kBuildFacilities;
var protected UIBuildItem m_kBuildItem;
var UIContinentSelect m_kContinentSelect;
var UIChooseFacility m_kChooseFacility;
var UIChooseTech m_kChooseTech;
var UIDebrief m_kDebriefUI;
var protected UIDisplayMovie m_kDisplayMovie;
var protected UIEndOfMonthReport m_kEoMReport;
var protected UIFoundry m_kFoundryUI;
var protected UIGeneLab m_kGeneLab;
var protected UICyberneticsLab m_kCyberneticsLab;
var protected UISoldierAugmentation m_kAugmentSoldier;
var protected UIGollop m_kGollopUI;
var protected UIGreyMarket m_kGreyMarket;
var protected UIHiring_Barracks m_kBarracksHiring;
var protected UIHiring_Hangar m_kHangarHiring;
var protected UIInterceptionEngagement m_kInterceptionEngagement;
var protected SwfMovie m_kInterceptionMovie;
var protected UIInfiltratorMission m_kInfiltratorMission;
var UIManufacturing m_kManufacturing;
var UIMECInventory m_kMECInventory;
var protected UIMECUpgrade m_kMECUpgrade;
var protected UIMedals m_kMedals;
var protected UIMemorial m_kMemorial;
var protected UIObjectivesPopup m_kObjectivePopupUI;
var protected UIOTS m_kOTS;
var protected UIPendingRequests m_kPendingRequestsUI;
var protected UIPsiLabs m_kPsiLabsUI;
var UIShipList m_kShipList;
var protected UIShipLoadout m_kShipLoadout;
var UIShipSummary m_kShipSummary;
var protected UIShellStrategy m_kShellStrategy;
var UISituationRoom m_kSituationRoom;
var protected UIFundingCouncilRequest m_kFundingCouncilRequest;
var protected UIFundingCouncilMission m_kFundingCouncilMission;
var UISquadSelect m_kSquadSelect;
var UIStrategyHUD m_kStrategyHUD;
var UIStrategyHUD_FacilitySubMenu m_kSubMenu;
var protected UIRecap m_kRecapUI;
var protected UIScienceLabs m_kScienceLabs;
var protected UISoldierCustomize m_kSoldierCustomize;
var UISoldierListBase m_kSoldierList;
var UISoldierLoadout m_kSoldierLoadout;
var UISoldierPromotion m_kSoldierPromote;
var UISoldierGeneMods m_kSoldierGeneMods;
var UISoldierGeneModsHUD m_kSoldierGeneModsHUD;
var UISoldierSummary m_kSoldierSummary;
var UISpecialUnlockDialogue m_kSpecialUnlockDialogue;
var UITellMeMore m_kTellMeMore;
var private array<XGScreenMgr> m_arrScreenMgrs;
var array<EMedalType> m_arrMedalUnlocks;
var array<EMedalType> m_arrMedalAwards;
var UIMissionControl m_kUIMissionControl;
var int m_iFacilityView;
var int m_iFirstTickerMsgIndex;
var transient bool m_bRecentlyPlayedPromotions;
var bool bShouldUpdateSituationRoomMenu;
var bool bShowMissionCounter;
var bool bShouldPause;
var private bool m_bHasRequestedInterceptionLoad;
var bool m_bIsShuttling;
var private XGInterception m_kXGInterception;

defaultproperties
{
    m_eUIMode=eUIMode_Strategy
}