/*******************************************************************************
 * XComHeadquartersCheatManager generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XComHeadquartersCheatManager extends XComCheatManager within XComHeadquartersController;

var bool bSeeAll;
var bool bDoGlobeView;
var bool bFreeCam;
var bool bDebugAIEvents;
var bool bAllowDeluge;
var bool bDumpSkelPoseUpdates;
var ECharacter iForceAlienType;
var private XGEntity kEntity;

defaultproperties
{
    bDoGlobeView=true
}