/*******************************************************************************
 * XGFacility_Barracks generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGFacility_Barracks extends XGFacility
    config(GameData)
    notplaceable
    hidecategories(Navigation);

enum ELastMissionResult
{
    eLastResult_None,
    eLastResult_Bad,
    eLastResult_Good,
    eLastResult_MAX
};

struct TMedal
{
    var EMedalType m_eType;
    var EPerkType m_ePowerA;
    var EPerkType m_ePowerB;
    var int m_iMaxAwards;
    var int m_iMissions;
};

struct Medal
{
    var string m_Name;
    var EMedalType m_eType;
    var EPerkType m_eChosenPower;
    var int m_iAvailable;
    var int m_iUsed;
    var int m_iMissionsLeft;
};

struct MedalRequirements
{
    var int m_iNumAbductions;
    var bool m_bSoldierKilledOrCritWounded;
    var array<EContinent> m_arrContinentMissions;
    var int m_iNumTerrorMissions;
    var int m_iNumCovertOpsMissions;
    var int m_iNumSpecialMissions;
    var bool m_bHQAssaultComplete;
};

struct RecycledMedals
{
    var int m_iNumMissions;
    var array<EMedalType> m_arrMedalsToRecycle;
};

struct CheckpointRecord_XGFacility_Barracks extends CheckpointRecord
{
    var XGStrategySoldier m_kVolunteer;
    var array<XGStrategySoldier> m_arrSoldiers;
    var array<XGStrategySoldier> m_aLastMissionSoldiers;
    var XGStrategySoldier m_kLastMissionCovertOperative;
    var array<int> m_arrOTSUpgrades;
    var array<XGStrategySoldier> m_arrFallen;
    var XGFacility_PsiLabs m_kPsiLabs;
    var XGFacility_GeneLabs m_kGeneLabs;
    var XGFacility_CyberneticsLab m_kCyberneticsLab;
    var int m_iSoldierCounter;
    var int m_iTankCounter;
    var int m_iAlloyTankCounter;
    var int m_iHoverTankCounter;
    var int m_iHighestRank;
    var int m_iHighestPsiRank;
    var int m_iHighestMecRank;
    var int m_iCapacity;
    var ELastMissionResult m_eLastResult;
    var EXComSpeakerType m_eLastResultSpeaker;
    var int m_iMoreSoldiersCounter;
    var bool m_bVolunteerUrged;
    var Medal m_arrMedals[EMedalType];
    var MedalRequirements m_kMedalRequirements;
    var MedalBattleData m_kMedalBattleData;
    var array<RecycledMedals> m_arrRecycledMedals;
    var array<ESoldierClass> m_arrClassWaitingList;
};

var config int NUM_RECYCLE_MISSIONS;
var config int NUM_INTERNATIONAL_SERVICE_CONTINENTS;
var config int NUM_MEDALOFHONOR_MISSIONS;
var config int NUM_PER_CLASS_DISTRIBUTION;
var config int NUM_REMOVE_CLASS_DISTRIBUTION;
var XGStrategySoldier m_kVolunteer;
var array<XGStrategySoldier> m_arrSoldiers;
var array<XGStrategySoldier> m_aLastMissionSoldiers;
var XGStrategySoldier m_kLastMissionCovertOperative;
var array<XGStrategySoldier> m_arrFallen;
var array<int> m_arrOTSUpgrades;
var XGFacility_PsiLabs m_kPsiLabs;
var XGFacility_GeneLabs m_kGeneLabs;
var XGFacility_CyberneticsLab m_kCyberneticsLab;
var int m_iSoldierCounter;
var int m_iTankCounter;
var int m_iAlloyTankCounter;
var int m_iHoverTankCounter;
var int m_iCapacity;
var int m_iHighestRank;
var int m_iHighestMecRank;
var int m_iHighestPsiRank;
var int m_aLastFemaleVoice[ECharacterLanguage];
var int m_aLastMaleVoice[ECharacterLanguage];
var ELastMissionResult m_eLastResult;
var EXComSpeakerType m_eLastResultSpeaker;
var int m_iMoreSoldiersCounter;
var bool m_bVolunteerUrged;
var bool m_bNotifyPromotions;
var transient bool bInitingNewGame;
var privatewrite Medal m_arrMedals[EMedalType];
var privatewrite MedalRequirements m_kMedalRequirements;
var privatewrite MedalBattleData m_kMedalBattleData;
var private array<RecycledMedals> m_arrRecycledMedals;
var private array<ESoldierClass> m_arrClassWaitingList;
var privatewrite TMedal m_arrTMedals[EMedalType];
var XGCharacterGenerator m_kCharGen;
var XGFacility_Lockers m_kLockers;
var XComPerkManager m_kPerkManager;
var private XGStrategySoldier m_kAwardCeremonySoldier;
var private int m_iAwardCeremonyPreviousLocation;
var const localized string m_strSHIVPrefix;
var const localized string m_strAlloySHIVPrefix;
var const localized string m_strHoverSHIVPrefix;
var const localized string m_strKIADateTimeFormat;
var const localized string m_arrMedalNames[11];