/*******************************************************************************
 * XGFacility_SpecialCases generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGFacility_SpecialCases extends XGFacility
    config(GameData)
    notplaceable
    hidecategories(Navigation);