/*******************************************************************************
 * XGFacility_GeneLabs generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGFacility_GeneLabs extends XGFacility
    config(GameData)
    notplaceable
    hidecategories(Navigation);

struct TGeneLabsPatient
{
    var XGStrategySoldier m_kSoldier;
    var array<int> m_arrHoursLeft;
    var array<EPerkType> m_arrPendingGeneMods;
};

struct CheckpointRecord_XGFacility_GeneLabs extends CheckpointRecord
{
    var array<TGeneLabsPatient> m_arrPatients;
};

var const localized string m_strCompletionDialogText;
var privatewrite array<TGeneLabsPatient> m_arrPatients;
var privatewrite bool m_bDoingFirstNarrative;
var privatewrite bool m_bIsPlayingCinematic;
var private transient XGStrategySoldier GeneModCinematicSoldier;
var private transient XComNarrativeMoment PendingNarrativeMoment;
var private transient PhysicsAsset GeneModCinematicPhysics;