/*******************************************************************************
 * XGHangarShip_Firestorm generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGHangarShip_Firestorm extends XGHangarShip
    hidecategories(Navigation);