/*******************************************************************************
 * XGHeadquartersUI generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGHeadquartersUI extends XGScreenMgr
    config(GameData)
    notplaceable
    hidecategories(Navigation);

enum eHQView
{
    eHQView_MainMenu,
    eHQView_MAX
};

struct THQHeader
{
    var array<TText> arrBulletins;
    var TLabeledText txtCash;
};

struct THQMainMenu
{
    var TMenu mnuOptions;
};

var THQHeader m_kHeader;
var THQMainMenu m_kMainMenu;