/*******************************************************************************
 * XGHeadquartersUI generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGHeadquartersUI extends XGScreenMgr
    config(GameData)
    notplaceable
    hidecategories(Navigation);

enum eHQView
{
    eHQView_MainMenu,
    eHQView_MAX
};

struct THQHeader
{
    var array<TText> arrBulletins;
    var TLabeledText txtCash;

    structdefaultproperties
    {
        arrBulletins=none
        txtCash=(StrValue="",strLabel="",iState=0,bNumber=false)
    }
};

struct THQMainMenu
{
    var TMenu mnuOptions;

    structdefaultproperties
    {
        mnuOptions=(strLabel="",arrOptions=none,bTakesNoInput=false)
    }
};

var THQHeader m_kHeader;
var THQMainMenu m_kMainMenu;