/*******************************************************************************
 * XGMission_ExaltRaid generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGMission_ExaltRaid extends XGMission
    config(GameData)
    notplaceable
    hidecategories(Navigation);