/*******************************************************************************
 * XGObjectiveManager generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGObjectiveManager extends XGStrategyActor
    config(GameData)
    notplaceable
    hidecategories(Navigation);

struct CheckpointRecord
{
    var EGameObjective m_eObjective;
    var bool m_bObjectiveAnnounced;
};

var EGameObjective m_eObjective;
var bool m_bObjectiveAnnounced;