/*******************************************************************************
 * XGOTSUI generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGOTSUI extends XGScreenMgr
    config(GameData)
    notplaceable
    hidecategories(Navigation);

enum EOTSView
{
    eOTSView_Table,
    eOTSView_MAX
};

struct TOTSHeader
{
    var TText txtTitle;
    var array<TLabeledText> arrResources;
};

struct TTableItemSummary
{
    var TText txtTitle;
    var TText txtSummary;
    var TImage imgOption;
};

struct TFacilityTable
{
    var TTableMenu mnuOptions;
    var array<TTableItemSummary> arrSummaries;
};

var TOTSHeader m_kHeader;
var TFacilityTable m_kTable;
var array<int> m_arrResources;
var array<TOTSTech> m_arrTechs;
var const localized string m_strLabelOTS;
var const localized string m_strPurchased;