/*******************************************************************************
 * XGPromotionUI generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGPromotionUI extends XGScreenMgr
    config(GameData)
    notplaceable
    hidecategories(Navigation);

enum ePromotionView
{
    ePromotionView_Tree,
    ePromotionView_MAX
};

struct TPromotionHeader
{
    var TText txtTitle;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
    }
};

struct TPromotionWelcome
{
    var TText txtTitle;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
    }
};

struct TPerkTree
{
    var int iRows;
    var int iColumns;
    var array<TGraphNode> m_arrPerks;

    structdefaultproperties
    {
        iRows=0
        iColumns=0
        m_arrPerks=none
    }
};

var TPromotionHeader m_kHeader;
var TPerkTree m_kTree;
var XGStrategySoldier m_kSoldier;
var int m_iHighlightX;
var int m_iHighlightY;