/*******************************************************************************
 * XGSatelliteSitRoomUI generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGSatelliteSitRoomUI extends XGScreenMgr
    config(GameData)
    notplaceable
    hidecategories(Navigation)
    implements(IFCRequestInterface);

enum ESatelliteView
{
    eSatelliteView_Main,
    eSatelliteView_Confirm,
    eSatelliteView_Bonus,
    eSatelliteView_Alert,
    eSatelliteView_Help,
    eSatelliteView_MAX
};

struct TSatelliteUI
{
    var TMenu mnuSatellites;
    var TButtonText btxtRotate;
    var TLabeledText ltxtCapacity;
    var TButtonText btxtExit;
    var int Current;
    var int Max;

    structdefaultproperties
    {
        mnuSatellites=(strLabel="",arrOptions=none,bTakesNoInput=false)
        btxtRotate=(StrValue="",iState=0,iButton=0)
        ltxtCapacity=(StrValue="",strLabel="",iState=0,bNumber=false)
        btxtExit=(StrValue="",iState=0,iButton=0)
        Current=0
        Max=0
    }
};

struct TSatCursorUI
{
    var bool bEnabled;
    var TButtonText txtHelp;

    structdefaultproperties
    {
        bEnabled=false
        txtHelp=(StrValue="",iState=0,iButton=0)
    }
};

struct TSatCountryUI
{
    var TText txtCountry;
    var TText txtFunding;
    var int iPanicLevel;
    var bool bHasSatCoverage;

    structdefaultproperties
    {
        txtCountry=(StrValue="",iState=0)
        txtFunding=(StrValue="",iState=0)
        iPanicLevel=0
        bHasSatCoverage=false
    }
};

struct TSatContinentUI
{
    var TText txtContinent;
    var TText txtInterceptors;
    var array<TText> arrBonuses;
    var array<TText> arrBonusLabels;
    var int iHighlightedBonus;

    structdefaultproperties
    {
        txtContinent=(StrValue="",iState=0)
        txtInterceptors=(StrValue="",iState=0)
        arrBonuses=none
        arrBonusLabels=none
        iHighlightedBonus=0
    }
};

struct TSatNodeUI
{
    var TButtonText btxtHelp;
    var TText txtCountry;
    var TText txtFunding;
    var TText txtPanicLabel;
    var int iPanicLevel;
    var TText txtContinent;
    var array<TText> arrBonuses;
    var array<TText> arrBonusLabels;
    var TText txtWarning;
    var bool bEnabled;
    var bool bEmpty;

    structdefaultproperties
    {
        btxtHelp=(StrValue="",iState=0,iButton=0)
        txtCountry=(StrValue="",iState=0)
        txtFunding=(StrValue="",iState=0)
        txtPanicLabel=(StrValue="",iState=0)
        iPanicLevel=0
        txtContinent=(StrValue="",iState=0)
        arrBonuses=none
        arrBonusLabels=none
        txtWarning=(StrValue="",iState=0)
        bEnabled=false
        bEmpty=false
    }
};

struct TSatAlert
{
    var TText txtTitle;
    var TText txtBody;
    var TImage imgAlert;
    var TMenu mnuOptions;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        txtBody=(StrValue="",iState=0)
        imgAlert=(iImage=0,strLabel="",iState=0,strPath="")
        mnuOptions=(strLabel="",arrOptions=none,bTakesNoInput=false)
    }
};

struct TSatHelp
{
    var TText txtTitle;
    var TText txtBody;
    var TButtonText btxtOk;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        txtBody=(StrValue="",iState=0)
        btxtOk=(StrValue="",iState=0,iButton=0)
    }
};

struct TSatFCAlert
{
    var TImage imgAlert;
    var TText txtFunding;
    var TText txtContinent;
    var TText txtBonus;
    var TButtonText txtContinue;

    structdefaultproperties
    {
        imgAlert=(iImage=0,strLabel="",iState=0,strPath="")
        txtFunding=(StrValue="",iState=0)
        txtContinent=(StrValue="",iState=0)
        txtBonus=(StrValue="",iState=0)
        txtContinue=(StrValue="",iState=0,iButton=0)
    }
};

struct TSatConfirm
{
    var TImage imgAlert;
    var TText txtTitle;
    var TText txtCountryLabel;
    var TText txtTravelTimeLabel;
    var TText txtFundingLabel;
    var TText txtCountry;
    var TText txtTravelTime;
    var TText txtFunding;
    var TText txtContinentCollection;
    var TLabeledText txtSpecialists;
    var TButtonText btxtLaunch;
    var TButtonText btxtCancel;

    structdefaultproperties
    {
        imgAlert=(iImage=0,strLabel="",iState=0,strPath="")
        txtTitle=(StrValue="",iState=0)
        txtCountryLabel=(StrValue="",iState=0)
        txtTravelTimeLabel=(StrValue="",iState=0)
        txtFundingLabel=(StrValue="",iState=0)
        txtCountry=(StrValue="",iState=0)
        txtTravelTime=(StrValue="",iState=0)
        txtFunding=(StrValue="",iState=0)
        txtContinentCollection=(StrValue="",iState=0)
        txtSpecialists=(StrValue="",strLabel="",iState=0,bNumber=false)
        btxtLaunch=(StrValue="",iState=0,iButton=0)
        btxtCancel=(StrValue="",iState=0,iButton=0)
    }
};

struct TSatBonusUI
{
    var TText txtTitle;
    var TText txtBonusName;
    var TText txtBonusDesc;
    var TButtonText btxtOk;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        txtBonusName=(StrValue="",iState=0)
        txtBonusDesc=(StrValue="",iState=0)
        btxtOk=(StrValue="",iState=0,iButton=0)
    }
};

var TSatelliteUI m_kUI;
var TSatAlert m_kAlert;
var TSatNodeUI m_kSatNodeUI;
var TSatCursorUI m_kCursorUI;
var TSatCountryUI m_kCountryUI;
var TSatContinentUI m_kContinentUI;
var TSatHelp m_kHelp;
var TSatConfirm m_kConfirm;
var TSatBonusUI m_kBonusUI;
var int m_iHighlighted;
var int m_iCountry;
var int m_iContinent;
var bool m_bLaunched;
var bool m_bWarnUplinkCapacity;
var TFCRequest m_tCompletedSatelliteRequest;
var const localized string m_strLabelUplinkCapacity;
var const localized string m_strLabelNoSatellitesToLaunch;
var const localized string m_strLabelAwaitingLaunch;
var const localized string m_strLabelNoInterceptorsInRegion;
var const localized string m_strLabelNoInterceptorsInRange;
var const localized string m_strLabelCarryOn;
var const localized string m_strLabelSatelliteTitle;
var const localized string m_strLabelSatelliteBody;
var const localized string m_strLabelContinue;
var const localized string m_strLabelOk;
var const localized string m_strLabelBonusInRegion;
var const localized string m_strLabelNoSatellites;
var const localized string m_strLabelHasSatellite;
var const localized string m_strLabelLaunchSatellite;
var const localized string m_strLabelDays;
var const localized string m_strLabelPerMonth;
var const localized string m_strLabelInterceptors;
var const localized string m_strLabelCurrent;
var const localized string m_strLabelNew;
var const localized string m_strSatSingular;
var const localized string m_strSatPlural;
var const localized string m_strLabelBonus;
var const localized string m_strLabelConfirmLaunch;
var const localized string m_strLabelCountry;
var const localized string m_strLabelTravelTime;
var const localized string m_strLabelFundingIncrease;
var const localized string m_strLabelMonitoring;
var const localized string m_strLabelReward;
var const localized string m_strLabelLaunchSatelliteLower;
var const localized string m_strLabelCancelSatelliteLower;
var const localized string m_strLabelScientist;
var const localized string m_strLabelEngineer;
var const localized string m_strLabelScientists;
var const localized string m_strLabelEngineers;
var const localized string m_strLabelNoCapacity;
var const localized string m_strLabelLeftXCom;