/*******************************************************************************
 * XGSituationRoomUI generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGSituationRoomUI extends XGScreenMgr
    config(GameData)
    notplaceable
    hidecategories(Navigation);

enum ESitView
{
    eSitView_Main,
    eSitView_Mission,
    eSitView_Request,
    eSitView_RequestComplete,
    eSitView_Satellites,
    eSitView_Finances,
    eSitView_GreyMarket,
    eSitView_NewObjective,
    eSitView_PendingRequests,
    eSitView_RequestAccepted,
    eSitView_RequestExpired,
    eSitView_ObjectivesMoreInfo,
    eSitView_Exalt,
    eSitView_CovertOpsExtractionMission,
    eSitView_MAX
};

enum ESitCountryState
{
    eSitCountry_Normal,
    eSitCountry_Withdrawn,
    eSitCountry_MAX
};

enum ETickerText
{
    eTickerTxt_SitRoomActive,
    ETickerText_MAX
};

enum EMapItem
{
    eMapItem_HQ,
    eMapItem_GroundedPlanes,
    eMapItem_Hangar,
    eMapItem_Jet,
    eMapItem_AlienBase,
    eMapItem_TempleShip,
    eMapItem_UFO,
    eMapItem_Outpost,
    eMapItem_Satellite,
    eMapItem_Cell,
    eMapItem_Cell_Agent,
    eMapItem_Cell_Ready,
    eMapItem_Cell_AnimateIn,
    eMapItem_Cell_AnimateOut,
    eMapItem_Cell_AnimateOutOperative,
    eMapItem_MAX
};

enum EUICellState
{
    EUI_CELL_ACTIVE,
    EUI_CELL_AGENT_OUT,
    EUI_CELL_AGENT_DONE,
    EUI_CELL_DESTROYED,
    EUI_CELL_NONE,
    EUI_CELL_MAX
};

struct TObjectivesUI
{
    var TText txtTitle;
    var array<TText> arrSubObjectivesUI;
    var TGameObjective kObjective;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        arrSubObjectivesUI=none
        kObjective=(eType=EGameObjective.eObj_None,eStatus=EObjectiveStatus.eObjStatus_NotStarted,strName="",eObjImage=EImage.eImage_None,arrSubObjectives=none)
    }
};

struct TObjectivesInDepthUI
{
    var TText txtTitle;
    var array<TText> arrSubObjectivesTitle;
    var array<TText> arrSubObjectivesInDepth;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        arrSubObjectivesTitle=none
        arrSubObjectivesInDepth=none
    }
};

struct TSitCountry
{
    var TText txtName;
    var Color clrPanic;
    var int iPanic;
    var ESitCountryState eState;
    var TText txtFunding;
    var int iEnum;
    var bool bClearedByClues;
    var bool bShowExaltBase;
    var EUICellState eCellState;
};

struct TSitCode
{
    var bool bActive;
    var bool bComplete;
    var TText txtTitle;
    var int iTotal;
    var int iCurrent;

    structdefaultproperties
    {
        bActive=false
        bComplete=false
        txtTitle=(StrValue="",iState=0)
        iTotal=0
        iCurrent=0
    }
};

struct TSitDoom
{
    var int iCountriesLost;
    var int iLimit;
    var TText txtTitle;

    structdefaultproperties
    {
        iCountriesLost=0
        iLimit=0
        txtTitle=(StrValue="",iState=0)
    }
};

struct TSitMoney
{
    var TLabeledText ltxtMoney;
    var TLabeledText ltxtIncome;

    structdefaultproperties
    {
        ltxtMoney=(StrValue="",strLabel="",iState=0,bNumber=false)
        ltxtIncome=(StrValue="",strLabel="",iState=0,bNumber=false)
    }
};

struct TSitTicker
{
    var array<TText> arrTickerText;

    structdefaultproperties
    {
        arrTickerText=none
    }
};

struct TSitRequest
{
    var TText txtTitle;
    var TImage imgBG;
    var TText txtIntro;
    var TLabeledText ltxtDueDate;
    var TLabeledText ltxtRequired;
    var TLabeledText ltxtItemDisplay;
    var TText txtRewardLabel;
    var array<TText> arrRewards;
    var TButtonText txtAccept;
    var TButtonText txtSellNow;
    var TButtonText txtIgnore;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        imgBG=(iImage=0,strLabel="",iState=0,strPath="")
        txtIntro=(StrValue="",iState=0)
        ltxtDueDate=(StrValue="",strLabel="",iState=0,bNumber=false)
        ltxtRequired=(StrValue="",strLabel="",iState=0,bNumber=false)
        ltxtItemDisplay=(StrValue="",strLabel="",iState=0,bNumber=false)
        txtRewardLabel=(StrValue="",iState=0)
        arrRewards=none
        txtAccept=(StrValue="",iState=0,iButton=0)
        txtSellNow=(StrValue="",iState=0,iButton=0)
        txtIgnore=(StrValue="",iState=0,iButton=0)
    }
};

struct TSitRequestComplete
{
    var TImage imgBG;
    var TText txtComplete;
    var TText txtRewardLabel;
    var array<TText> arrRewards;
    var TButtonText txtAccept;

    structdefaultproperties
    {
        imgBG=(iImage=0,strLabel="",iState=0,strPath="")
        txtComplete=(StrValue="",iState=0)
        txtRewardLabel=(StrValue="",iState=0)
        arrRewards=none
        txtAccept=(StrValue="",iState=0,iButton=0)
    }
};

struct TSitMission
{
    var TText txtTitle;
    var TText txtSubTitle;
    var TText txtTopSecretLabel;
    var TImage imgBG;
    var TText txtDescription;
    var TText txtRewardLabel;
    var array<TText> arrRewards;
    var TButtonText txtAccept;
    var TButtonText txtCancel;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        txtSubTitle=(StrValue="",iState=0)
        txtTopSecretLabel=(StrValue="",iState=0)
        imgBG=(iImage=0,strLabel="",iState=0,strPath="")
        txtDescription=(StrValue="",iState=0)
        txtRewardLabel=(StrValue="",iState=0)
        arrRewards=none
        txtAccept=(StrValue="",iState=0,iButton=0)
        txtCancel=(StrValue="",iState=0,iButton=0)
    }
};

struct TInfiltratorMission
{
    var TText txtTitle;
    var TText txtSubTitle;
    var TText txtTopSecretLabel;
    var TImage imgBG;
    var TText txtDescription;
    var TText txtRewardLabel;
    var array<TText> arrRewards;
    var TButtonText txtAccept;
    var TButtonText txtCancel;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        txtSubTitle=(StrValue="",iState=0)
        txtTopSecretLabel=(StrValue="",iState=0)
        imgBG=(iImage=0,strLabel="",iState=0,strPath="")
        txtDescription=(StrValue="",iState=0)
        txtRewardLabel=(StrValue="",iState=0)
        arrRewards=none
        txtAccept=(StrValue="",iState=0,iButton=0)
        txtCancel=(StrValue="",iState=0,iButton=0)
    }
};

struct TNewObjectiveUI
{
    var TText txtTitle;
    var TText txtText;
    var TText txtHelp;
    var TButtonText btxtOk;
    var TImage imgObj;

    structdefaultproperties
    {
        txtTitle=(StrValue="",iState=0)
        txtText=(StrValue="",iState=0)
        txtHelp=(StrValue="",iState=0)
        btxtOk=(StrValue="",iState=0,iButton=0)
        imgObj=(iImage=0,strLabel="",iState=0,strPath="")
    }
};

struct TMapItemUI
{
    var EMapItem eType;
    var float X;
    var float Y;
    var int Amount;

    structdefaultproperties
    {
        eType=EMapItem.eMapItem_HQ
        X=0.0
        Y=0.0
        Amount=0
    }
};

var TMenu m_mnuMain;
var array<XGSituationRoomUI.ESitView> m_arrOptions;
var TObjectivesUI m_kObjectivesUI;
var TObjectivesInDepthUI m_kObjectivesInDepthUI;
var array<TSitCountry> m_arrCountriesUI;
var TSitCode m_kCodeUI;
var TSitMoney m_kMoney;
var TSitTicker m_kTicker;
var TSitMission m_kMission;
var TInfiltratorMission m_kInfiltratorMission;
var TSitRequest m_kRequest;
var TSitRequestComplete m_kComplete;
var TSitDoom m_kDoom;
var array<TMapItemUI> m_mapItemsUI;
var const localized string m_strMissionTitleLabel;
var const localized string m_strLabelAcceptMission;
var const localized string m_strLabelRefuseMission;
var const localized string m_strLabelRequested;
var const localized string m_strLabelTimeLimit;
var const localized string m_strLabelDays;
var const localized string m_strLabelRewards;
var const localized string m_strLabelCarryOn;
var const localized string m_strLabelSellItemDate;
var const localized string m_strLabelIgnoreRequest;
var const localized string m_strLabelCompletedRequest;
var const localized string m_strLabelOk;
var const localized string m_strLabelAcceptPendingRequest;
var const localized string m_strLabelNewRecruit;
var const localized string m_strLabelLaunchSatellite;
var const localized string m_strLabelMonitorUFO;
var const localized string m_strLabelInfiltratorMode;
var const localized string m_strLabelInfiltratorHelp;
var const localized string m_strLabelNoSatToLaunch;
var const localized string m_strLabelViewFinances;
var const localized string m_strLabelViewExpenditures;
var const localized string m_stdLabelVisitGreyMarket;
var const localized string m_stdLabelVisitGreyMarketHelp;
var const localized string m_strLabelPendingRequests;
var const localized string m_strLabelPendingRequestsHelp;
var const localized string m_strLabelObjectives;
var const localized string m_strLabelCodeDecryption;
var const localized string m_strLabelCodeDecrypted;
var const localized string m_strLabelNewObjective;
var const localized string m_strNumAlienCodePiece;
var const localized string m_strNumEngineers;
var const localized string m_strNumScientists;
var const localized string m_strNumSatellite;
var const localized string m_strReducePanic;
var const localized string m_strNumElerium;
var const localized string m_strNumExaltIntel;
var const localized string m_strInProgress;
var const localized string m_strComplete;