/*******************************************************************************
 * XGWander generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGWander extends Actor
    notplaceable
    hidecategories(Navigation);

const HUGE_ISLAND = 257;
const LARGE_ISLAND = 129;
const MEDIUM_ISLAND = 65;
const SMALL_ISLAND = 33;
const HEIGHT_DEEP = 3;
const HEIGHT_SHALLOW = 5;
const HEIGHT_GRASS = 11;
const HEIGHT_HILLS = 13;
const HEIGHT_MOUNTAINS = 15;

enum eTerrainType
{
    eTerrain_None,
    eTerrain_WaterDeep,
    eTerrain_WaterShallow,
    eTerrain_Beach,
    eTerrain_Grass,
    eTerrain_Hills,
    eTerrain_Mountains,
    eTerrain_MAX
};

struct TPoint
{
    var int X;
    var int Y;

    structdefaultproperties
    {
        X=0
        Y=0
    }
};

struct TBeing
{
    var int iHP;
    var int iAttack;
    var TPoint ptLoc;

    structdefaultproperties
    {
        iHP=0
        iAttack=0
        ptLoc=(X=0,Y=0)
    }
};

struct TRegion
{
    var TRect kRect;
    var int iWidth;
    var int iHeight;
    var array<XGWander.eTerrainType> arrTiles;
    var array<TBeing> arrBeings;

    structdefaultproperties
    {
        kRect=(fLeft=0.0,fTop=0.0,fRight=0.0,fBottom=0.0)
        iWidth=0
        iHeight=0
        arrTiles=none
        arrBeings=none
    }
};

var TRegion m_kWorld;
var TBeing m_kHero;